[lints]
workspace = true

[package]
name = "oxideterm-session-adapter"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
oxideterm-remote-desktop = { path = "../oxideterm-remote-desktop" }
oxideterm-connections = { path = "../oxideterm-connections" }
oxideterm-settings = { path = "../oxideterm-settings" }
oxideterm-sftp = { path = "../oxideterm-sftp" }
oxideterm-ssh = { path = "../oxideterm-ssh" }
oxideterm-terminal = { path = "../oxideterm-terminal" }

[dev-dependencies]
chrono.workspace = true

[target.'cfg(not(target_os = "macos"))'.dev-dependencies]
keyring.workspace = true
