[lints]
workspace = true

[package]
name = "oxideterm-gpui-editor"
edition.workspace = true
license.workspace = true
version.workspace = true

[features]
default = []

[dependencies]
gpui.workspace = true
oxideterm-gpui-ui = { path = "../oxideterm-gpui-ui" }
tracing.workspace = true
serde.workspace = true
oxideterm-editor-core = { path = "../oxideterm-editor-core" }
oxideterm-editor-syntax = { path = "../oxideterm-editor-syntax" }
oxideterm-plugin-manifest = { path = "../oxideterm-plugin-manifest" }
oxideterm-theme = { path = "../oxideterm-theme" }
unicode-segmentation.workspace = true
unicode-width.workspace = true

[dev-dependencies]
tempfile = "3"
zip.workspace = true
serde_json.workspace = true
sha2.workspace = true
gpui = { workspace = true, features = ["test-support"] }
