use crate::args::*;

pub(crate) fn command_name(command: &Command) -> Option<&'static str> {
    match command {
        Command::Settings(command) => Some(match &command.action {
            SettingsAction::Path(..) => "settings path",
            SettingsAction::Sections(..) => "settings sections",
            SettingsAction::Validate(..) => "settings validate",
            SettingsAction::Show(..) => "settings show",
            SettingsAction::Get(..) => "settings get",
            SettingsAction::Set(..) => "settings set",
            SettingsAction::Unset(..) => "settings unset",
            SettingsAction::Apply(..) => "settings apply",
            SettingsAction::Import(..) => "settings import",
            SettingsAction::Export(..) => "settings export",
            SettingsAction::Diff(..) => "settings diff",
        }),
        Command::Connections(command) => Some(match &command.action {
            ConnectionsAction::List(..) => "connections list",
            ConnectionsAction::Show(..) => "connections show",
            ConnectionsAction::Open(..) => "connections open",
            ConnectionsAction::Groups(..) => "connections groups",
            ConnectionsAction::Search(..) => "connections search",
            ConnectionsAction::Export(..) => "connections export",
            ConnectionsAction::Diff(..) => "connections diff",
            ConnectionsAction::Validate(..) => "connections validate",
            ConnectionsAction::Create(..) => "connections create",
            ConnectionsAction::Edit(..) => "connections edit",
            ConnectionsAction::Delete(..) => "connections delete",
            ConnectionsAction::Rename(..) => "connections rename",
            ConnectionsAction::Import(..) => "connections import",
            ConnectionsAction::ApplySnapshot(..) => "connections apply-snapshot",
            ConnectionsAction::Group(..) => "connections group",
        }),
        Command::Forwards(command) => Some(match &command.action {
            ForwardsAction::List(..) => "forwards list",
            ForwardsAction::Show(..) => "forwards show",
            ForwardsAction::Create(..) => "forwards create",
            ForwardsAction::Edit(..) => "forwards edit",
            ForwardsAction::Delete(..) => "forwards delete",
            ForwardsAction::Validate(..) => "forwards validate",
            ForwardsAction::Export(..) => "forwards export",
            ForwardsAction::Import(..) => "forwards import",
        }),
        Command::QuickCommands(command) => Some(match &command.action {
            QuickCommandsAction::List(..) => "quick-commands list",
            QuickCommandsAction::Show(..) => "quick-commands show",
            QuickCommandsAction::Create(..) => "quick-commands create",
            QuickCommandsAction::Edit(..) => "quick-commands edit",
            QuickCommandsAction::Delete(..) => "quick-commands delete",
            QuickCommandsAction::Export(..) => "quick-commands export",
            QuickCommandsAction::Import(..) => "quick-commands import",
        }),
        Command::Plugins(command) => Some(match &command.action {
            PluginsAction::List(..) => "plugins list",
            PluginsAction::Settings(..) => "plugins settings",
            PluginsAction::Enable(..) => "plugins enable",
            PluginsAction::Disable(..) => "plugins disable",
        }),
        Command::Secrets(command) => Some(match &command.action {
            SecretsAction::Status(..) => "secrets status",
            SecretsAction::Set(..) => "secrets set",
            SecretsAction::Clear(..) => "secrets clear",
            SecretsAction::Import(..) => "secrets import",
        }),
        Command::Oxide(command) => Some(match &command.action {
            OxideAction::Validate(..) => "oxide validate",
            OxideAction::PreviewImport(..) => "oxide preview-import",
            OxideAction::Diff(..) => "oxide diff",
            OxideAction::Import(..) => "oxide import",
            OxideAction::Export(..) => "oxide export",
        }),
        Command::CloudSync(command) => Some(match &command.action {
            CloudSyncAction::Status(..) => "cloud-sync status",
            CloudSyncAction::Configure(..) => "cloud-sync configure",
            CloudSyncAction::Preview(..) => "cloud-sync preview",
            CloudSyncAction::Diff(..) => "cloud-sync diff",
            CloudSyncAction::Push(..) => "cloud-sync push",
            CloudSyncAction::Pull(..) => "cloud-sync pull",
            CloudSyncAction::Apply(..) => "cloud-sync apply",
            CloudSyncAction::Resolve(..) => "cloud-sync resolve",
            CloudSyncAction::State(..) => "cloud-sync state",
            CloudSyncAction::History(..) => "cloud-sync history",
            CloudSyncAction::Backups(..) => "cloud-sync backups",
            CloudSyncAction::Secrets(..) => "cloud-sync secrets",
            CloudSyncAction::Backend(..) => "cloud-sync backend",
        }),
        Command::Backup(command) => Some(match &command.action {
            BackupAction::Preview(..) => "backup preview",
            BackupAction::Create(..) => "backup create",
            BackupAction::List(..) => "backup list",
            BackupAction::Inspect(..) => "backup inspect",
            BackupAction::Verify(..) => "backup verify",
            BackupAction::Restore(..) => "backup restore",
            BackupAction::Diff(..) => "backup diff",
        }),
        Command::Batch(command) => Some(match &command.action {
            BatchAction::Apply(..) => "batch apply",
        }),
        Command::Ssh(_) => Some("ssh dispatch"),
        Command::Open(_) => Some("open dispatch"),
        Command::Report(_) => Some("report"),
        Command::Mcp(_) => Some("mcp"),
        Command::Portable(_) => Some("portable"),
        _ => None,
    }
}
